### PR TITLE
[0.8.x] compilation: add missing POSITION_INDEPENDENT_CODE

### PR DESCRIPTION
**Pull request by neonsoftware**
Some libraries within this project **do set** the CMake POSITION_INDEPENDENT_CODE**, ex. workflow_utils.

Other libraries **depend** on these libraries, such as workflow_data_utils, therefore, they need to set position independence as well.

This commit **fixes compilation issues** seen first in OpenWRT on device update 0.8.0.

Thank you in advance.

### CODE REVIEW

**Comment by neonsoftware** [comment]
Hi. How do I access the logs on Azure Devops for the failing builds ?

Thanks in advance.

**Comment by neonsoftware** [comment]
I have tried logging in with a Github account but got a "**401 - Uh-oh, you do not have access.**"

**Comment by neonsoftware** [comment]
This PR has also been rebased on develop and reformatted as #184

**Comment by jw-msft** [comment]
Opened this PR to merge this one from your fork into develop: https://github.com/Azure/iot-hub-device-update/pull/184

**Pull request closed without merging**
