### PR TITLE
Fix crash when printing NULL work folder

### PR DESCRIPTION
**Pull request by parsodark**
Printing NULL with the %s specified is undefined behavior
and causes a crash with some compilers.

### CODE REVIEW

**Comment by jw-msft** [comment]
closing to align with branching strategy

**Comment by jw-msft** [comment]
sorry, wrong pr in tab.

**Review by shiyi-peng — APPROVED** [review]

**Comment by shiyi-peng** [comment]
@parsodark Hi Pierrick, can you merge from a branch inside the repo instead of a branch in a fork of the repo? Our build pipeline is targeting to run any branch in this repo, so as you see it failed to run any fork. Thank you for your collaboration!

**Comment by parsodark** [comment]
@shiyi-peng Same as https://github.com/Azure/iot-hub-device-update/pull/80: I do not have write access to this repo & can you advise if the changes should go in main or release/2021-q2? Thank you!

**Comment by jw-msft** [comment]
@parsodark  I manually integrated into [develop branch](https://github.com/Azure/iot-hub-device-update/compare/develop) as [commit 7285503](https://github.com/Azure/iot-hub-device-update/commit/7285503511172021e5f450683443f6bbe0ff7088) and put you as co-contributor in commit message.

**Pull request closed without merging**
