### PR TITLE
Bug 32367663: Relax special chars restrictions on DeviceInfo

### PR DESCRIPTION
**Pull request by shiyi-peng**
Aligning with this change ADU-M's fix: Bug 32192452: Relax compat info DeviceManufacturer and DeviceModel restrictions

~~**Pending:** Leo is still waiting to hear back from IoT team on the length restrictions here:~~
~~Restrictions on device Manufacturer and model? · Issue #153 · Azure/iot-plugandplay-models (github.com)~~
Confirmed: The length limit remains 64

### CODE REVIEW

**Comment by nihemstr** [comment]
>  * 2. alphanumeric, dot and dash only.

Need to remove this line to reflect current changes (probably need to similarly change the .h) 

---
Refers to: src/agent/device_info_interface/src/device_info_interface.c:86 in a9412bb. [](commit_id = a9412bb7c9a3473bb915c9fa1b39c73caf55765f, deletion_comment = False)

**Review by nihemstr — CHANGES_REQUESTED** [review]
:clock1:

**Review by JeffMill — APPROVED** [review]
:shipit:

**Review by nihemstr — APPROVED** [review]
:shipit:

**Pull request merged**
