### PR TITLE
Add ARM64 Cross-Compilation to Windows Build Pipeline

### PR DESCRIPTION
**Pull request by jw-msft**
- Add steps to cross-compile ARM64 and generate 2 additional ARM64 build artifacts
- Address comments from the previous PR

### CODE REVIEW

**Comment by shiyi-peng** [comment]
The Jobs name is "Job", seems like a default job name, maybe can have a better naming?https://dev.azure.com/azure-device-update/adu-linux-client/_build/results?buildId=13037&view=results

**Review by shiyi-peng — APPROVED** [review]
I think the ARM build failing will be resolved once rebased on master. This should be good to go

**Comment by jw-msft** [comment]
> The Jobs name is "Job", seems like a default job name, maybe can have a better naming?https://dev.azure.com/azure-device-update/adu-linux-client/_build/results?buildId=13037&view=results

Thanks for suggesting this! It led me to create separate jobs for amd64 and arm64 and will push commit here if it works.  It looks much better now.

image

**Comment by jw-msft** [comment]
> I think the ARM build failing will be resolved once rebased on master. This should be good to go

@shiyi-peng Good to know, thank you. I will try merging upstream develop into the feature branch after merging this and see if that fixes those.

**Pull request merged**
